import pandas as pd
import numpy as np
import joblib
import datetime
import matplotlib.pyplot as plt
import os

# =========================================================
# 🔥 1. LOAD RANDOM FOREST MODEL & ASSETS
# =========================================================
# Ensure these files were generated by your updated Random Forest training script
model = joblib.load("RF_lag_model.pkl")
scaler = joblib.load("RF_lag_scaler.pkl")
features = joblib.load("RF_lag_features.pkl")

# =========================================================
# 🔥 2. FETCH DATA (FIXED FOR MALAYSIA TIME)
# =========================================================
def get_recent_data(channel_id, read_key, minutes=1000):
    # Force UTC+8 (Malaysia Time) for the request
    tz_offset = datetime.timezone(datetime.timedelta(hours=8))
    end = datetime.datetime.now(tz_offset)
    start = end - datetime.timedelta(minutes=minutes)

    start_str = start.strftime('%Y-%m-%d%%20%H:%M:%S')
    end_str = end.strftime('%Y-%m-%d%%20%H:%M:%S')

    url = f'https://api.thingspeak.com/channels/{channel_id}/feeds.csv?api_key={read_key}&start={start_str}&end={end_str}'
    df = pd.read_csv(url)

    df.rename(columns={
        'field1': 'V', 'field2': 'I', 'field3': 'T', 'field4': 'H2_actual'
    }, inplace=True)

    # Convert ThingSpeak UTC to Malaysia Time and strip timezone info
    df['created_at'] = pd.to_datetime(df['created_at']).dt.tz_convert('Asia/Kuala_Lumpur').dt.tz_localize(None)

    df = df.set_index('created_at')
    # Use ffill to handle missing minutes in continuous stream
    df = df.resample('1min').mean().fillna(method='ffill').reset_index()

    return df

# Load Data
ts_read_id = os.getenv('THINGSPEAK_READ_ID', '3321400')
ts_read_key = os.getenv('THINGSPEAK_READ_KEY', '4Q4YD3ZW21602X7L')
df = get_recent_data(ts_read_id, ts_read_key, minutes=1000)

# =========================================================
# 🔥 3. PHYSICS PREPARATION
# =========================================================
df['theo_H2'] = (df['I'] / 2 / 96500) * 24.4651 * 1000 * 60
df['target_err'] = df['theo_H2'] - df['H2_actual']

history = df.copy().reset_index(drop=True)
if len(history) < 40:
    raise ValueError("❌ Not enough data (>40 rows required)")

# =========================================================
# 🔥 4. FORECAST LOOP (RANDOM FOREST LOGIC)
# =========================================================
future_steps = 7 * 24 * 60
predictions = []

latest_row = history.iloc[-1]
base_V = latest_row['V']
base_I = latest_row['I']
base_T = latest_row['T']
start_time = latest_row['created_at']

# Extract starting error history for lag features
error_history = history['target_err'].tolist()

print(f"🚀 Generating 7-day Random Forest forecast...")

for step in range(future_steps):
    v_sim = base_V
    i_sim = base_I
    
    # B. DIURNAL TEMPERATURE CYCLE (24-hour sine wave)
    t_sim = base_T
    
    # C. LAG FEATURES
    lag1, lag2, lag5, lag30 = error_history[-1], error_history[-2], error_history[-5], error_history[-30]
    ma10 = np.mean(error_history[-10:])
    
    # D. RF PREDICTION
    feat_row = np.array([[v_sim, i_sim, t_sim, lag1, lag2, lag5, lag30, ma10]])
    X_scaled = scaler.transform(feat_row)
    pred_err = model.predict(X_scaled)[0]
    
    # E. PHYSICS RECONSTRUCTION
    theo = (i_sim / 2 / 96500) * 24.4651 * 1000 * 60
    h2_base = theo - pred_err
    
    # Logical Bounds: Force to 0 if negative, cap at 65 (or 100 per sensor specs)
    h2_final = np.clip(h2_base, 0, 65)
    
    # F. TIMESTAMP (Fixed Malaysia Time Baseline)
    next_time = start_time + pd.Timedelta(minutes=step + 1)
    
    predictions.append({'time': next_time, 'H2_pred': h2_final})
    
    # Update error history for the next iteration
    error_history.append(pred_err)

# =========================================================
# 🔥 5. SMART MERGE, SAVE & PLOT
# =========================================================
pred_df = pd.DataFrame(predictions)
file_path = "RF_prediction.csv"

# 1. Load existing data if it exists
if os.path.exists(file_path):
    try:
        old_df = pd.read_csv(file_path)
        old_df['time'] = pd.to_datetime(old_df['time'])
        
        # 2. Combine old and new data
        # We put pred_df (new) after old_df so that new values are preferred
        combined_df = pd.concat([old_df, pred_df], ignore_index=True)
        
        # 3. Deduplicate: If timestamps overlap, keep the LAST one (the new prediction)
        # This keeps past history while updating future values with the latest forecast
        combined_df = combined_df.drop_duplicates(subset=['time'], keep='last')
        
        # 4. Sort by time and limit size (Optional: Keep last 30 days to prevent huge files)
        combined_df = combined_df.sort_values('time')
        
        # Optional: Uncomment the line below to keep only the last 45,000 minutes (~1 month)
        # combined_df = combined_df.tail(45000) 
        
        final_df = combined_df
        print(f"🔄 Merged {len(pred_df)} new predictions with existing history.")
    except Exception as e:
        print(f"⚠️ Error loading old CSV, starting fresh: {e}")
        final_df = pred_df
else:
    print("🆕 No existing CSV found. Creating new one.")
    final_df = pred_df

# 5. Save the combined results
final_df.to_csv(file_path, index=False)
print(f"✅ Saved updated rolling predictions to {file_path}")

# --- Plotting ---
def plot_forecast(df):
    plt.figure(figsize=(15, 6))
    # We plot the last 10,000 minutes so the plot doesn't get too crowded
    plot_data = df.tail(10080) 
    plt.plot(plot_data['time'], plot_data['H2_pred'], color='blue', linewidth=0.8)
    plt.title("H2 Forecast: Past History + 7-Day Future (Updated Every 5m)")
    plt.ylabel("H2 (mL/min)")
    plt.xlabel("Time")
    plt.grid(True, alpha=0.3)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

plot_forecast(final_df)
