import pandas as pd
import numpy as np
import joblib
import datetime
import matplotlib.pyplot as plt
import os

# =========================================================
# 🔥 1. LOAD RANDOM FOREST MODEL & ASSETS
# =========================================================
# Ensure these files were generated by your updated Random Forest training script
model = joblib.load("RF_lag_model.pkl")
scaler = joblib.load("RF_lag_scaler.pkl")
features = joblib.load("RF_lag_features.pkl")

# =========================================================
# 🔥 2. FETCH DATA (FIXED FOR MALAYSIA TIME)
# =========================================================
def get_recent_data(channel_id, read_key, minutes=1000):
    # Force UTC+8 (Malaysia Time) for the request
    tz_offset = datetime.timezone(datetime.timedelta(hours=8))
    end = datetime.datetime.now(tz_offset)
    start = end - datetime.timedelta(minutes=minutes)

    start_str = start.strftime('%Y-%m-%d%%20%H:%M:%S')
    end_str = end.strftime('%Y-%m-%d%%20%H:%M:%S')

    url = f'https://api.thingspeak.com/channels/{channel_id}/feeds.csv?api_key={read_key}&start={start_str}&end={end_str}'
    df = pd.read_csv(url)

    df.rename(columns={
        'field1': 'V', 'field2': 'I', 'field3': 'T', 'field4': 'H2_actual'
    }, inplace=True)

    # Convert ThingSpeak UTC to Malaysia Time and strip timezone info
    df['created_at'] = pd.to_datetime(df['created_at']).dt.tz_convert('Asia/Kuala_Lumpur').dt.tz_localize(None)

    df = df.set_index('created_at')
    # Use ffill to handle missing minutes in continuous stream
    df = df.resample('1min').mean().fillna(method='ffill').reset_index()

    return df

# Load Data
ts_read_id = os.getenv('THINGSPEAK_READ_ID', '3321400')
ts_read_key = os.getenv('THINGSPEAK_READ_KEY', '4Q4YD3ZW21602X7L')
df = get_recent_data(ts_read_id, ts_read_key, minutes=1000)

# =========================================================
# 🔥 3. PHYSICS PREPARATION
# =========================================================
df['theo_H2'] = (df['I'] / 2 / 96500) * 24.4651 * 1000 * 60
df['target_err'] = df['theo_H2'] - df['H2_actual']

history = df.copy().reset_index(drop=True)
if len(history) < 40:
    raise ValueError("❌ Not enough data (>40 rows required)")

# =========================================================
# 🔥 4. FORECAST LOOP (RANDOM FOREST LOGIC)
# =========================================================
future_steps = 7 * 24 * 60
predictions = []

latest_row = history.iloc[-1]
base_V = latest_row['V']
base_I = latest_row['I']
base_T = latest_row['T']
start_time = latest_row['created_at']

# Extract starting error history for lag features
error_history = history['target_err'].tolist()

print(f"🚀 Generating 7-day Random Forest forecast...")

for step in range(future_steps):
    v_sim = base_V
    i_sim = base_I
    
    # B. DIURNAL TEMPERATURE CYCLE (24-hour sine wave)
    t_sim = base_T
    
    # C. LAG FEATURES
    lag1, lag2, lag5, lag30 = error_history[-1], error_history[-2], error_history[-5], error_history[-30]
    ma10 = np.mean(error_history[-10:])
    
    # D. RF PREDICTION
    feat_row = np.array([[v_sim, i_sim, t_sim, lag1, lag2, lag5, lag30, ma10]])
    X_scaled = scaler.transform(feat_row)
    pred_err = model.predict(X_scaled)[0]
    
    # E. PHYSICS RECONSTRUCTION
    theo = (i_sim / 2 / 96500) * 24.4651 * 1000 * 60
    h2_base = theo - pred_err
    
    # Logical Bounds: Force to 0 if negative, cap at 65 (or 100 per sensor specs)
    h2_final = np.clip(h2_base, 0, 65)
    
    # F. TIMESTAMP (Fixed Malaysia Time Baseline)
    next_time = start_time + pd.Timedelta(minutes=step + 1)
    
    predictions.append({'time': next_time, 'H2_pred': h2_final})
    
    # Update error history for the next iteration
    error_history.append(pred_err)

# =========================================================
# 🔥 5. SAVE & PLOT
# =========================================================
pred_df = pd.DataFrame(predictions)
file_path = "RF_prediction.csv" # Renamed to reflect the model change

# Force Overwrite to prevent Merge Conflicts in GitHub Actions
pred_df.to_csv(file_path, index=False)

print(f"✅ Saved Random Forest predictions to {file_path}")

def plot_forecast(df):
    plt.figure(figsize=(15, 6))
    plt.plot(df['H2_pred'].values, color='green', linewidth=0.8) # Changed to green for RF
    plt.title("7-Day Continuous H2 Forecast (Random Forest Model, Fixed Timezone)")
    plt.ylabel("H2 (mL/min)")
    plt.xlabel("Minutes")
    plt.grid(True, alpha=0.3)
    plt.show()

plot_forecast(pred_df)
