name: ANN Daily Train

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows you to run it manually from the "Actions" tab

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Training Script
        run: python ANN_train.py

      - name: Upload Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ann-model-files  # Unique name
          path: |
            ANN_lag_model.pkl
            ANN_lag_scaler.pkl
            ANN_lag_features.pkl
          retention-days: 7
