name: 5-Min Predict
on:
  schedule: [{cron: "*/5 * * * *"}]
  workflow_dispatch:
jobs:
  predict:
    runs-on: ubuntu-latest
    # Wait for the model to exist
    steps:
      - uses: actions/checkout@v4
      - name: Download Model from Training Workflow
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: train.yml            # The name of your training file
          name: model-files              # Must match the name in train.yml exactly
          latest_status: completed       # Only get the model if training finished
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - run: pip install -r requirements.txt
      - env:
          PBI_URL: ${{ secrets.PBI_URL }}
        run: python predict.py
